---

- name: Join node to Kubernetes master
  shell: >
    {{ kubernetes_join_command }}
    creates=/etc/kubernetes/kubelet.conf
  tags: ['skip_ansible_lint']



- name: Setup kubeconfig folder for root
  command: "mkdir -p /root/.kube"

- name: Copy config file to root config folder
  copy:
    src: "/tmp/config"
    dest: "/root/.kube/"

- name: Check for user
  shell: egrep "^{{ provision_cluster_user }}:" /etc/passwd
  register: user_exists

- name: Setup kubeconfig for cluster user
  command: "{{ item }}"
  with_items:
   - "mkdir -p /home/{{ provision_cluster_user }}/.kube"
  when: user_exists

- name: Copy config file
  copy:
    src: "/tmp/config"
    dest: "/home/{{ provision_cluster_user }}/.kube/"
    owner: "{{ provision_cluster_user }}"
  when: user_exists
